### ISSUE TITLE
SASS does not compile

### ISSUE THREAD

**Issue by BananaAcid** [Wscats/compile-hero#11]
`.sass` files do not compile. (`.scss` does.)

**Comment by Wscats** [comment]
The sass suffix is ​​used less and can be supported in the future. @BananaAcid

**Comment by BananaAcid** [comment]
I do not mean the suffix, I am actually talking about the syntax, that is used more commonly then the scss syntax. @Wscats

**Comment by Wscats** [comment]
I checked the source code and found that it supports sass. Can you provide the sass file you tested? @BananaAcid
