### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JaroslavasKar** [Wscats/compile-hero#16]
- Issue Type: `Performance`
- Extension Name: `qf`
- Extension Version: `6.8.51`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\karma\Wscats.qf-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Wscats** [comment]
@JaroslavasKar You can update the version and see if there is any improvement😁
