### ISSUE TITLE
Using SASS syntax doesn't work but SCSS works

### ISSUE THREAD

**Issue by huytrvan** [Wscats/compile-hero#17]
I have this sample SASS code 
```sass
// my_file.sass

.container
    color: white
```

When I save it, the extension returns this error message:
> Invalid CSS after ".": expected 1 selector or at-rule was ".container"

However, when I use SCSS syntax in a SASS file, it compiles:
```scss
// my_file.sass

.container {
    color: white;
}
```

Here's my setting:
```js
    "compile-hero.pug-output-directory": "./html",
    "compile-hero.sass-output-directory": "./css",
    "compile-hero.less-output-toggle": false,
    "compile-hero.jade-output-toggle": false,
    "compile-hero.typescript-output-toggle": false,
    "compile-hero.scss-output-toggle": false,
    "compile-hero.javascript-output-toggle": false,
```

Can you please check? Thank you...

**Comment by Wscats** [comment]
@huytrvan hello, I have fixed this place. Fix indented syntax which it can treat code as `sass` (as opposed to `scss`), Hope it helps you😁

![Kapture 2020-05-20 at 11 34 10](https://user-images.githubusercontent.com/17243165/82402007-eddd7000-9a8d-11ea-8bbe-1dd0ec2c45f9.gif)

**Comment by huytrvan** [comment]
Hi, I fixed this by restarting Vscode maybe the extension didn't update the file extension properly. Thanks you!

**Comment by Raouljf** [comment]
Can't find stylesheet to import`
![Capture d’écran du 2020-09-03 09-02-20](https://user-images.githubusercontent.com/46252310/92088112-5a257a80-edc4-11ea-9b1f-9778207506ab.png)
`

**Comment by Raouljf** [comment]
Can't find stylesheet to import
![Capture d’écran du 2020-09-03 09-02-20](https://user-images.githubusercontent.com/46252310/92088222-7fb28400-edc4-11ea-89d6-309ad46428b9.png)

**Comment by Wscats** [comment]
> Can't find stylesheet to import
> ![Capture d’écran du 2020-09-03 09-02-20](https://user-images.githubusercontent.com/46252310/92088222-7fb28400-edc4-11ea-89d6-309ad46428b9.png)

Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass. https://github.com/sass/node-sass/issues/2362
