### ISSUE TITLE
Pug "include" doesn`t compile

### ISSUE THREAD

**Issue by Rimcore** [Wscats/compile-hero#18]
heelp pls:)
![2020-05-19_19-45-59](https://user-images.githubusercontent.com/25361362/82354388-677f4a80-9a09-11ea-9bc3-a29f776a0de5.png)

![2020-05-19_19-40-52](https://user-images.githubusercontent.com/25361362/82354149-1cfdce00-9a09-11ea-98d0-16312fca01ab.png)

**Comment by Wscats** [comment]
@Rimcore Sorry, the introduction of external files is temporarily unsupportable, I will improve it in the future.

**Comment by Rimcore** [comment]
Thank you:)
