### ISSUE TITLE
PUG does not compile

### ISSUE THREAD

**Issue by clevett** [Wscats/compile-hero#3]
SCSS is working as expected but PUG does not compile. With my setup the are both compiling to the same directory.  No errors are reported and I believe it is simply not compiling at all.

**Comment by Wscats** [comment]
@clevett Click to open the extension management interface Configure Extension Settings, You can change the path of the project compilation directory, or toggle the switch of language -> https://github.com/Wscats/compile-hero#Configuration.

'PUG does not compile' -> Can you tell me the environment and system you are running, I tested it is OK, is there a syntax error?
