### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Scarabow** [Wscats/compile-hero#42]
- Issue Type: `Bug`
- Extension Name: `eno`
- Extension Version: `2.3.2`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.48.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 23939,
		"activateCallTime": 1,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Wscats.eno",
				"_lower": "wscats.eno"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Scarabow** [comment]
Could you let me know why this was closed without a reply

**Comment by Wscats** [comment]
> Could you let me know why this was closed without a reply

I did not see the detailed problem from the data reported above. Can you describe the specific performance of the problem easily? Thank you😁
