### ISSUE TITLE
Typescript Compile Bug

### ISSUE THREAD

**Issue by s-ashutosh-b** [Wscats/compile-hero#55]
The typescript file is compiling successfully, but a notification appear on right bottom that says there's a compile error. There actually isn't.

**Comment by Wscats** [comment]
> The typescript file is compiling successfully, but a notification appear on right bottom that says there's a compile error. There actually isn't.

Is it convenient to provide your `.ts` source file code?

**Comment by S-AshutoshDev** [comment]
![image](https://user-images.githubusercontent.com/68853189/92377814-5f672a00-f122-11ea-9a3c-a4a955656455.png)
![image](https://user-images.githubusercontent.com/68853189/92377950-93dae600-f122-11ea-84b0-567b0baa1720.png)

Doesn't matter what ever I write. It just keeps popping up that error message.
It just contain a `console.log(true)` just that.

**Comment by Wscats** [comment]
> ![image](https://user-images.githubusercontent.com/68853189/92377814-5f672a00-f122-11ea-9a3c-a4a955656455.png)
> ![image](https://user-images.githubusercontent.com/68853189/92377950-93dae600-f122-11ea-84b0-567b0baa1720.png)
> 
> Doesn't matter what ever I write. It just keeps popping up that error message.
> It just contain a `console.log(true)` just that.

I fixed it here, you can update and try again.

**Comment by s-ashutosh-b** [comment]
Thanks! It's Fixed. 
Good Luck.

**Comment by s-ashutosh-b** [comment]
On the bottom left corner, there's still the error message. although there isn't any error notification .
![image](https://user-images.githubusercontent.com/68853189/92561381-bdfee600-f291-11ea-8a72-5c3b34ccfc07.png)
