### ISSUE TITLE
How set ES6 (TypeScript compiler)

### ISSUE THREAD

**Issue by Chocopieca** [Wscats/compile-hero#57]
How I can set ES6 when compiling .ts to .js ?

**Comment by Chocopieca** [comment]
I fined it. I've made file tsconfig.json in same folder with firle .ts and written this:
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"lib": [
			"es6"
		]
}

**Comment by Wscats** [comment]
> How I can set ES6 when compiling .ts to .js ?

You're right👍

**Comment by s-ashutosh-b** [comment]
Can you make ES6 default transpiled format?

**Comment by Wscats** [comment]
> Can you make ES6 default transpiled format?

It is recommended to leave it to the user to set it up.

**Comment by s-ashutosh-b** [comment]
At least give an option in extension settings to choose the version to be compiled to.
