### ISSUE TITLE
Featur requested

### ISSUE THREAD

**Issue by s-ashutosh-b** [Wscats/compile-hero#58]
I don't want pop-up notification in bottom right corner. May be a notification toggle option may help.

**Comment by Wscats** [comment]
> I don't want pop-up notification in bottom right corner. May be a notification toggle option may help.

This is a good suggestion, I will consider implementing it in the next version.

**Comment by Wscats** [comment]
> notification

Here Example `settings.json` file:
```js
{
  "compile-hero": {
    "notification-toggle": false,
  }
}
```

**Comment by s-ashutosh-b** [comment]
Thanks!
