### ISSUE TITLE
为什么我在win10是使用.pug-output-directory不起作用

### ISSUE THREAD

**Issue by ziliang2016** [Wscats/compile-hero#76]
使用jade就可以正常编译"compile-hero.jade-output-directory": "../dist",

**Comment by ziliang2016** [comment]
![01](https://user-images.githubusercontent.com/24588995/99646807-ec682100-2a8b-11eb-9a75-69287ac67475.jpg)

**Comment by Wscats** [comment]
> 使用jade就可以正常编译"compile-hero.jade-output-directory": "../dist",

没起作用是指没编译成功还是没编译到指定的dist目录还是其他呢？是否设置了 `compile-hero.pug-output-toggle` 选项

**Comment by ziliang2016** [comment]
> compile-hero.pug-output-toggle

设置了compile-hero.pug-output-toggle，是没有进行编译

**Comment by Wscats** [comment]
> > compile-hero.pug-output-toggle
> 
> 设置了compile-hero.pug-output-toggle，是没有进行编译



> > compile-hero.pug-output-toggle
> 
> 设置了compile-hero.pug-output-toggle，是没有进行编译

如果 `compile-hero.pug-output-toggle` 设置了 `false` 则不会触发编译。

**Comment by ziliang2016** [comment]
谢谢，
  "compile-hero.pug-output-toggle": true,
  "compile-hero.jade-output-toggle": true,
  "compile-hero.pug-output-directory": "../dist",
  "compile-hero.jade-output-directory": "../dist",
只有jade编译了，pug没有进行编译
