### ISSUE TITLE
关于compile一个less的问题

### ISSUE THREAD

**Issue by hongcyu** [Wscats/compile-hero#80]
进行less编译，单独编译less文件可以使用，但是编译main.less(也就是带有@import)就报错路径错误，不知道是什么原因
vscode v1.51.1
![QQ图片20201128185410](https://user-images.githubusercontent.com/41502466/100513857-2384b380-31ab-11eb-93f2-1f85c6df0ed4.png)
![QQ图片20201128185415](https://user-images.githubusercontent.com/41502466/100513859-24b5e080-31ab-11eb-9cfc-62c1f9b9ebcc.png)

**Comment by Wscats** [comment]
> 进行less编译，单独编译less文件可以使用，但是编译main.less(也就是带有@import)就报错路径错误，不知道是什么原因
> vscode v1.51.1
> ![QQ图片20201128185410](https://user-images.githubusercontent.com/41502466/100513857-2384b380-31ab-11eb-93f2-1f85c6df0ed4.png)
> ![QQ图片20201128185415](https://user-images.githubusercontent.com/41502466/100513859-24b5e080-31ab-11eb-9cfc-62c1f9b9ebcc.png)

看提醒是文件没找到，您可以粘贴下 `_plugin/hljs.less`的代码来看看吗，上面提醒这里15行出现了报错。

**Comment by hongcyu** [comment]
@Wscats 
hljs代码如下，不过需要提出的是我删除第15行就变成14行报错了，这个是一个博客主题项目，地址如下：https://github.com/halo-dev/halo-theme-hshan

`
/* for block of numbers */
.hljs-ln-numbers {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;

  text-align: center;
  color: #ccc;
  //border-right: 1px solid #CCC;
  vertical-align: top;
  padding-right: 5px;

  /* your custom style here */
}

/* for block of code */
.hljs-ln-code {
  padding-left: 10px !important;
}

td.hljs-ln-line.hljs-ln-numbers {
  width: 40px;
  text-align: center;
  background: rgba(200,200,200,0.15);
}

.hljs-ln td, .hljs-ln th {
  border: none;
  line-height: 1.6rem;
  font-size: 14px;
}

.hljs-ln tbody tr:nth-of-type(odd) {
  background-color: #fafafa;
}

.hljs {
  padding: 0 !important;
  font-family: Consolas, "Microsoft YaHei", sans-serif, "Source Code Pro";
}

.hljs-ln {
  margin: 0 auto;
}
`

**Comment by Wscats** [comment]
@hongcyu 
上个版本升级的时候增加了代码块选区编译，导致这个地方作用域丢失了，下个版本会修复(今晚会发新版哈)

**Comment by hongcyu** [comment]
@Wscats 好的，辛苦啦~

**Comment by Wscats** [comment]
> @Wscats 好的，辛苦啦~

已发布修复，更新版本(v2.3.33)再试试，如果能帮到你，给个五星好评哈😁https://marketplace.visualstudio.com/items?itemName=Wscats.eno&ssr=false#review-details。

**Comment by hongcyu** [comment]
@Wscats 已经5星好评~
