### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by thegamerx1** [Wscats/compile-hero#82]
Error: https://p.ahkscript.org/?p=5273652c
![image](https://user-images.githubusercontent.com/34986564/100544368-79ae3100-3255-11eb-9b80-cc0887b82995.png)
I have default settings
![image](https://user-images.githubusercontent.com/34986564/100544393-a19d9480-3255-11eb-99b8-1c26f2d36862.png)

**Comment by Wscats** [comment]
> Error: https://p.ahkscript.org/?p=5273652c
> ![image](https://user-images.githubusercontent.com/34986564/100544368-79ae3100-3255-11eb-9b80-cc0887b82995.png)
> I have default settings
> ![image](https://user-images.githubusercontent.com/34986564/100544393-a19d9480-3255-11eb-99b8-1c26f2d36862.png)

May I use this command to compile a folder or a single file? If it is a folder, you can describe in detail what is inside and whether any files have been compiled successfully.
