### ISSUE TITLE
2.3.40 broke support for Windows network drive compilation of SASS

### ISSUE THREAD

**Issue by lstenner** [Wscats/compile-hero#92]
Unfortunately, no errors or anything, it simply does not compile SASS.
Downgrading to 2.3.39 fixes it for now.

**Comment by Wscats** [comment]
> Unfortunately, no errors or anything, it simply does not compile SASS.
> Downgrading to 2.3.39 fixes it for now.

It may be caused by merge code https://github.com/Wscats/compile-hero/pull/88, I will roll back the version first.

**Comment by lstenner** [comment]
I can confirm that the rollback of #88 fixed it. Thanks for looking into the issue!
