### ISSUE TITLE
请问如何只保留压缩后的文件

### ISSUE THREAD

**Issue by MingOf** [Wscats/compile-hero#95]
比如我有style.scss。
编译完成后会有 style.min.css 和 style.css，但是我想让 style.css 默认就是压缩的，而不是再产生一个 style.min.css

**Comment by Wscats** [comment]
现在还不支持只生成压缩文件，这里可以考虑增加开关 `generate-minified-html-only` ，`generate-minified-css-only` 和 `generate-minified-javascript-only`，你看这样方便不？

**Comment by Wscats** [comment]
你好，最新版已经支持以下三个新的配置项`generate-minified-html-only` ，`generate-minified-css-only` 和 `generate-minified-javascript-only`：
```js
{
    "compile-hero.generate-minified-javascript": true,
    "compile-hero.generate-minified-javascript-only": true,
    "compile-hero.generate-minified-css": true,
    "compile-hero.generate-minified-css-only": true,
    "compile-hero.generate-minified-html": true,
    "compile-hero.generate-minified-html-only": true
}
```
如果能帮助到您，能否给我一个[五星好评](https://marketplace.visualstudio.com/items?itemName=Wscats.eno&ssr=false#review-details)呢，谢谢!

**Comment by MingOf** [comment]
给力给力，已五星
